### ISSUE TITLE
配列が0initか1initかでごちゃごちゃになっている

### ISSUE THREAD

**Issue by derushio** [narumi18wa/ItnavCoronaSDKBootcamp#1]

**Comment by cypher512** [comment]
* ボタン消去の実装記述が配置記述の手前にあり、わかりにくい
* ボタン配置の実装についてまとめて書いた後に、ボタンを消す話に移ると良い。

**Comment by cypher512** [comment]
- ブロックの配置が横ｘ縦=5 x 2列になっているため、ループのインデックス処理がわかりにくくなっているのが原因
- １始まりにするor ０始まりにする or ブロックを１列にする？など、コードの記述詳細も踏まえて要検討

**Comment by derushio** [comment]
ブロックの問題はこちらにまとめました。
https://github.com/narumi18wa/ItnavCoronaSDKBootcamp/issues/7

このプロジェクトはluaの仕様に基づき1initで統一することにします。
それに伴い、ブロックは一列、余裕のある人は二次元配列で管理することにします。

提案なのですが、応用のようなオプショナルな章を作っても良いかもしれません。

**Comment by cypher512** [comment]
> ブロックの問題はこちらにまとめました。

了解です。このIssueはCloseしてください。

> 応用のようなオプショナルな章を作っても良いかもしれません。

そうですね。質問が何件もあった画面遷移の話なども、そちらにまとめるといいかもしれません。

**Comment by TamaRabbits** [comment]
対応済
