### ISSUE TITLE
Bootcamp用としては、量が多すぎるかもしれない

### ISSUE THREAD

**Issue by cypher512** [narumi18wa/ItnavCoronaSDKBootcamp#6]
- 量を増やすと応用の範囲を広げられる反面、日程に間に合わなくなる懸念がある。
- 2016年度は結局全員１日で終えられ、また、最終発表では本教材のテクニックを流用した作品もいくつか見られた。
- 量はこれで適切かもしれないので、継続検討

**Comment by TamaRabbits** [comment]
解決済
