### ISSUE TITLE
教科書で完結するため、一人でできる人は先に進んでといってしまうと誰も話を聞かなくなってしまう

### ISSUE THREAD

**Issue by derushio** [narumi18wa/ItnavCoronaSDKBootcamp#8]
教科書としては良いのだけども、Bootcampとして味気ない。かといってできる人のスピードを落とすのもまた辛い。

**Comment by derushio** [comment]
教科書を先に配って理解できた人は一日目から自分のアプリを作ってもらう。
わからない人は授業を聞いてもらいながらゆっくりやる。

**Comment by TamaRabbits** [comment]
解決済
